image: 5003/centos-ansible-ci:2.1.x
pipelines:
  default:
    - step:
        script:
          - >
             build_push_image() {
               test ! -d $1 && git clone git@bitbucket.org:nhac/$1.git $1
               pushd $1 > /dev/null &&
                 git pull &&
                 . ./build.sh
               popd > /dev/null
             }
          - sshpass -p "${PROV_PASS}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null prov@neec.xyz "$(typeset -f); build_push_image $BITBUCKET_REPO_SLUG"