FROM registry.neec.xyz/neeco/buildpack-deps:curl
RUN apk add --no-cache --virtual .buildpack-deps \
                                 bzr \
                                 git \
                                 mercurial \
                                 openssh-client \
                                 subversion \
                                 procps